In [26]:
import utils
import xarray as xr
import numpy as np

In [2]:
f = utils.gen_fair_CO2_only(["ssp119"])

In [44]:
fill(f.emissions, 0)

da_emissions = xr.load_dataarray(utils.get_path("results/emissions.nc"))     
ssp_CO2_emissions = da_emissions.sel(specie=["CO2 FFI", "CO2 AFOLU"]).sum("specie")
ssp_CO2_emissions = ssp_CO2_emissions.sel(scenario=f.scenarios).squeeze("config", drop=True)

emissions_aligned, _ = xr.align(f.emissions, ssp_CO2_emissions, join='inner')
common_timepoints = emissions_aligned.timepoints
f.emissions.loc[dict(timepoints=common_timepoints, specie="CO2")] = ssp_CO2_emissions

In [25]:
common_timepoints = np.intersect1d(
    ssp_CO2_emissions['timepoints'].values,
    f.emissions['timepoints'].values
)

emissions_subset = f.emissions.sel(timepoints=common_timepoints)


AttributeError: 'numpy.ndarray' object has no attribute 'intersection'

In [11]:
ssp_CO2_emissions

<xarray.DataArray (timepoints: 750, scenario: 9, config: 1)>
array([[[2.02982580e-02],
        [2.02982580e-02],
        [2.02982580e-02],
        ...,
        [2.02982580e-02],
        [2.02982580e-02],
        [2.02982580e-02]],

       [[4.23838993e-02],
        [4.23838993e-02],
        [4.23838993e-02],
        ...,
        [4.23838993e-02],
        [4.23838993e-02],
        [4.23838993e-02]],

       [[6.44661875e-02],
        [6.44661875e-02],
        [6.44661875e-02],
        ...,
...
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [4.20240535e+01]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [4.20240535e+01]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        ...,
        [0.00000000e+00],
        [0.00000000e+00],
        [4.20240535e+01]]])
Coordinates:
  * timepoints  (timepoints) float64 1.75e+03 1.752e+03 ... 2.498e+03 2.5e+03
  * scenario    (scenario) <U11 'ssp119' 'ssp126' ... 'ssp585' 'historical'
  * config      (config) <U11 'unspecified'

In [9]:
f.emissions

<xarray.DataArray (timepoints: 1250, scenario: 1, config: 841, specie: 3)>
array([[[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
...
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]]])
Coordinates:
  * timepoints  (timepoints) float64 1.75e+03 1.752e+03 ... 2.998e+03 3e+03
  * scenario    (scenario) <U6 'ssp119'
  * config      (config) int64 1234 2451 5859 5883 ... 1592589 1594247 1597937
  * specie      (specie) <U3 'CO2' 'CH4' 'N2O'

<xarray.DataArray 'timepoints' (timepoints: 750)>
array([1750.5, 1751.5, 1752.5, ..., 2497.5, 2498.5, 2499.5])
Coordinates:
  * timepoints  (timepoints) float64 1.75e+03 1.752e+03 ... 2.498e+03 2.5e+03

In [3]:
f.emissions

<xarray.DataArray (timepoints: 1250, scenario: 1, config: 841, specie: 3)>
array([[[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
...
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]],


       [[[nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan],
         ...,
         [nan, nan, nan],
         [nan, nan, nan],
         [nan, nan, nan]]]])
Coordinates:
  * timepoints  (timepoints) float64 1.75e+03 1.752e+03 ... 2.998e+03 3e+03
  * scenario    (scenario) <U6 'ssp119'
  * config      (config) int64 1234 2451 5859 5883 ... 1592589 1594247 1597937
  * specie      (specie) <U3 'CO2' 'CH4' 'N2O'